[package]
name = "class-10"
version = "0.1.0"
authors = ["HINA KHADIM <hinakhadim2002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "1.0.0"
bson = "1.0.0"
serde_json = "1.0.55"